package com.otakup.niriko.ui.theme

import androidx.compose.ui.graphics.Color

// —— 绿色系主色调（浅色 / 深色共用种子色）——
val GreenPrimaryLight = Color(0xFF2E7D32)
val GreenOnPrimaryLight = Color(0xFFFFFFFF)
val GreenPrimaryContainerLight = Color(0xFFC8E6C9)
val GreenOnPrimaryContainerLight = Color(0xFF1B5E20)

val GreenSecondaryLight = Color(0xFF558B2F)
val GreenOnSecondaryLight = Color(0xFFFFFFFF)
val GreenSecondaryContainerLight = Color(0xFFDCEDC8)
val GreenOnSecondaryContainerLight = Color(0xFF33691E)

val GreenTertiaryLight = Color(0xFF00695C)
val GreenOnTertiaryLight = Color(0xFFFFFFFF)
val GreenTertiaryContainerLight = Color(0xFFB2DFDB)
val GreenOnTertiaryContainerLight = Color(0xFF004D40)

val GreenBackgroundLight = Color(0xFFF7FBF4)
val GreenOnBackgroundLight = Color(0xFF1A1C19)
val GreenSurfaceLight = Color(0xFFF7FBF4)
val GreenOnSurfaceLight = Color(0xFF1A1C19)
val GreenSurfaceVariantLight = Color(0xFFDEE5D8)
val GreenOnSurfaceVariantLight = Color(0xFF424940)
val GreenOutlineLight = Color(0xFF72796F)

// —— 深色主题 ——
val GreenPrimaryDark = Color(0xFF81C784)
val GreenOnPrimaryDark = Color(0xFF003910)
val GreenPrimaryContainerDark = Color(0xFF1B5E20)
val GreenOnPrimaryContainerDark = Color(0xFFC8E6C9)

val GreenSecondaryDark = Color(0xFFAED581)
val GreenOnSecondaryDark = Color(0xFF1B3700)
val GreenSecondaryContainerDark = Color(0xFF33691E)
val GreenOnSecondaryContainerDark = Color(0xFFDCEDC8)

val GreenTertiaryDark = Color(0xFF80CBC4)
val GreenOnTertiaryDark = Color(0xFF003731)
val GreenTertiaryContainerDark = Color(0xFF004D40)
val GreenOnTertiaryContainerDark = Color(0xFFB2DFDB)

val GreenBackgroundDark = Color(0xFF111411)
val GreenOnBackgroundDark = Color(0xFFE2E3DE)
val GreenSurfaceDark = Color(0xFF111411)
val GreenOnSurfaceDark = Color(0xFFE2E3DE)
val GreenSurfaceVariantDark = Color(0xFF424940)
val GreenOnSurfaceVariantDark = Color(0xFFC2C9BD)
val GreenOutlineDark = Color(0xFF8C9388)

// ==================== 预置主题色（浅色） ====================
// 中性背景/表面（各主题共用，避免换色后玻璃卡/背景失衡）
val NeutralBackgroundLight = Color(0xFFF8F9F7)
val NeutralOnBackgroundLight = Color(0xFF1A1C19)
val NeutralSurfaceLight = Color(0xFFF8F9F7)
val NeutralOnSurfaceLight = Color(0xFF1A1C19)
val NeutralSurfaceVariantLight = Color(0xFFDEE5D8)
val NeutralOnSurfaceVariantLight = Color(0xFF424940)
val NeutralOutlineLight = Color(0xFF72796F)

// 蓝
val BluePrimaryLight = Color(0xFF1565C0)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFBBDEFB)
val BlueOnPrimaryContainerLight = Color(0xFF0D47A1)
val BlueSecondaryLight = Color(0xFF0277BD)
val BlueOnSecondaryLight = Color(0xFFFFFFFF)
val BlueSecondaryContainerLight = Color(0xFFB3E5FC)
val BlueOnSecondaryContainerLight = Color(0xFF01579B)
val BlueTertiaryLight = Color(0xFF4527A0)
val BlueOnTertiaryLight = Color(0xFFFFFFFF)
val BlueTertiaryContainerLight = Color(0xFFD1C4E9)
val BlueOnTertiaryContainerLight = Color(0xFF311B92)

// 紫
val PurplePrimaryLight = Color(0xFF6A1B9A)
val PurpleOnPrimaryLight = Color(0xFFFFFFFF)
val PurplePrimaryContainerLight = Color(0xFFE1BEE7)
val PurpleOnPrimaryContainerLight = Color(0xFF4A148C)
val PurpleSecondaryLight = Color(0xFF7B1FA2)
val PurpleOnSecondaryLight = Color(0xFFFFFFFF)
val PurpleSecondaryContainerLight = Color(0xFFE8DAEF)
val PurpleOnSecondaryContainerLight = Color(0xFF4A0072)
val PurpleTertiaryLight = Color(0xFFC2185B)
val PurpleOnTertiaryLight = Color(0xFFFFFFFF)
val PurpleTertiaryContainerLight = Color(0xFFF8BBD0)
val PurpleOnTertiaryContainerLight = Color(0xFF880E4F)

// 橙
val OrangePrimaryLight = Color(0xFFE65100)
val OrangeOnPrimaryLight = Color(0xFFFFFFFF)
val OrangePrimaryContainerLight = Color(0xFFFFE0B2)
val OrangeOnPrimaryContainerLight = Color(0xFFBF360C)
val OrangeSecondaryLight = Color(0xFFEF6C00)
val OrangeOnSecondaryLight = Color(0xFFFFFFFF)
val OrangeSecondaryContainerLight = Color(0xFFFFF3E0)
val OrangeOnSecondaryContainerLight = Color(0xFFE65100)
val OrangeTertiaryLight = Color(0xFF6D4C41)
val OrangeOnTertiaryLight = Color(0xFFFFFFFF)
val OrangeTertiaryContainerLight = Color(0xFFD7CCC8)
val OrangeOnTertiaryContainerLight = Color(0xFF4E342E)

// 红
val RedPrimaryLight = Color(0xFFC62828)
val RedOnPrimaryLight = Color(0xFFFFFFFF)
val RedPrimaryContainerLight = Color(0xFFFFCDD2)
val RedOnPrimaryContainerLight = Color(0xFFB71C1C)
val RedSecondaryLight = Color(0xFFAD1457)
val RedOnSecondaryLight = Color(0xFFFFFFFF)
val RedSecondaryContainerLight = Color(0xFFF8BBD0)
val RedOnSecondaryContainerLight = Color(0xFF880E4F)
val RedTertiaryLight = Color(0xFF795548)
val RedOnTertiaryLight = Color(0xFFFFFFFF)
val RedTertiaryContainerLight = Color(0xFFD7CCC8)
val RedOnTertiaryContainerLight = Color(0xFF4E342E)

// 青
val TealPrimaryLight = Color(0xFF00695C)
val TealOnPrimaryLight = Color(0xFFFFFFFF)
val TealPrimaryContainerLight = Color(0xFFB2DFDB)
val TealOnPrimaryContainerLight = Color(0xFF004D40)
val TealSecondaryLight = Color(0xFF00838F)
val TealOnSecondaryLight = Color(0xFFFFFFFF)
val TealSecondaryContainerLight = Color(0xFFB2EBF2)
val TealOnSecondaryContainerLight = Color(0xFF006064)
val TealTertiaryLight = Color(0xFF5D4037)
val TealOnTertiaryLight = Color(0xFFFFFFFF)
val TealTertiaryContainerLight = Color(0xFFD7CCC8)
val TealOnTertiaryContainerLight = Color(0xFF3E2723)

// ==================== 预置主题色（深色） ====================
val NeutralBackgroundDark = Color(0xFF121412)
val NeutralOnBackgroundDark = Color(0xFFE2E3DE)
val NeutralSurfaceDark = Color(0xFF121412)
val NeutralOnSurfaceDark = Color(0xFFE2E3DE)
val NeutralSurfaceVariantDark = Color(0xFF424940)
val NeutralOnSurfaceVariantDark = Color(0xFFC2C9BD)
val NeutralOutlineDark = Color(0xFF8C9388)

// 蓝
val BluePrimaryDark = Color(0xFF90CAF9)
val BlueOnPrimaryDark = Color(0xFF0D47A1)
val BluePrimaryContainerDark = Color(0xFF0D47A1)
val BlueOnPrimaryContainerDark = Color(0xFFBBDEFB)
val BlueSecondaryDark = Color(0xFF4FC3F7)
val BlueOnSecondaryDark = Color(0xFF01579B)
val BlueSecondaryContainerDark = Color(0xFF01579B)
val BlueOnSecondaryContainerDark = Color(0xFFB3E5FC)
val BlueTertiaryDark = Color(0xFFB39DDB)
val BlueOnTertiaryDark = Color(0xFF311B92)
val BlueTertiaryContainerDark = Color(0xFF4527A0)
val BlueOnTertiaryContainerDark = Color(0xFFD1C4E9)

// 紫
val PurplePrimaryDark = Color(0xFFCE93D8)
val PurpleOnPrimaryDark = Color(0xFF4A148C)
val PurplePrimaryContainerDark = Color(0xFF4A148C)
val PurpleOnPrimaryContainerDark = Color(0xFFE1BEE7)
val PurpleSecondaryDark = Color(0xFFBA68C8)
val PurpleOnSecondaryDark = Color(0xFF4A0072)
val PurpleSecondaryContainerDark = Color(0xFF6A1B9A)
val PurpleOnSecondaryContainerDark = Color(0xFFE8DAEF)
val PurpleTertiaryDark = Color(0xFFF06292)
val PurpleOnTertiaryDark = Color(0xFF880E4F)
val PurpleTertiaryContainerDark = Color(0xFFC2185B)
val PurpleOnTertiaryContainerDark = Color(0xFFF8BBD0)

// 橙
val OrangePrimaryDark = Color(0xFFFFB74D)
val OrangeOnPrimaryDark = Color(0xFFBF360C)
val OrangePrimaryContainerDark = Color(0xFFBF360C)
val OrangeOnPrimaryContainerDark = Color(0xFFFFE0B2)
val OrangeSecondaryDark = Color(0xFFFFA726)
val OrangeOnSecondaryDark = Color(0xFFE65100)
val OrangeSecondaryContainerDark = Color(0xFFE65100)
val OrangeOnSecondaryContainerDark = Color(0xFFFFF3E0)
val OrangeTertiaryDark = Color(0xFFBCAAA4)
val OrangeOnTertiaryDark = Color(0xFF4E342E)
val OrangeTertiaryContainerDark = Color(0xFF6D4C41)
val OrangeOnTertiaryContainerDark = Color(0xFFD7CCC8)

// 红
val RedPrimaryDark = Color(0xFFEF9A9A)
val RedOnPrimaryDark = Color(0xFFB71C1C)
val RedPrimaryContainerDark = Color(0xFFB71C1C)
val RedOnPrimaryContainerDark = Color(0xFFFFCDD2)
val RedSecondaryDark = Color(0xFFF48FB1)
val RedOnSecondaryDark = Color(0xFF880E4F)
val RedSecondaryContainerDark = Color(0xFFAD1457)
val RedOnSecondaryContainerDark = Color(0xFFF8BBD0)
val RedTertiaryDark = Color(0xFFBCAAA4)
val RedOnTertiaryDark = Color(0xFF4E342E)
val RedTertiaryContainerDark = Color(0xFF795548)
val RedOnTertiaryContainerDark = Color(0xFFD7CCC8)

// 青
val TealPrimaryDark = Color(0xFF80CBC4)
val TealOnPrimaryDark = Color(0xFF004D40)
val TealPrimaryContainerDark = Color(0xFF004D40)
val TealOnPrimaryContainerDark = Color(0xFFB2DFDB)
val TealSecondaryDark = Color(0xFF4DD0E1)
val TealOnSecondaryDark = Color(0xFF006064)
val TealSecondaryContainerDark = Color(0xFF006064)
val TealOnSecondaryContainerDark = Color(0xFFB2EBF2)
val TealTertiaryDark = Color(0xFFBCAAA4)
val TealOnTertiaryDark = Color(0xFF3E2723)
val TealTertiaryContainerDark = Color(0xFF5D4037)
val TealOnTertiaryContainerDark = Color(0xFFD7CCC8)
